name: "Update the package version on pushes to main"
on:
  push:
    branches:
      - main
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./scripts/incrementMinor.js
      - run: ./scripts/incrementMinor.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Automated version bump on merge to main'