name: "Learn Github Actions: push to main"
on:
  push:
    branches:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [ '12', '14', '16' ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: 'npm'
  #     - run: npm install
  #     - run: npm test
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: echo "I am a job"
      - run: chmod +x ./scripts/node-script.js
      - run: ./scripts/node-script.js