name: "Learn Github Actions: Push all"
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install
      - run: npm test
  scripts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am a job"
      - run: "${GITHUB_WORKSPACE}/.github/scripts/node-script.js"