name: "Workflow for all pushes, except main"
on:
  push:
    branches-ignore:
      - main
jobs:
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
        # with:
        #   node-version: '14'
      - run: chmod +x ./scripts/increment-patch.js
      - run: ./scripts/increment-patch.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minor version bump'