name: "Workflow for all pushes, except main"
on:
  push:
    branches-ignore:
      - main
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node: [ '12', '14', '16' ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node }}
  #         cache: 'npm'
  #     - run: npm install
  #     - run: npm test
  scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: chmod +x ./scripts/increment-patch.js
      - run: ./scripts/increment-patch.js
      # - name: upload version number from increment
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: version
      #     path: temp-version.txt
      # - name: make version number from increment available
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: version
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Minor version bump'